-- Database + tables to test
DROP DATABASE IF EXISTS test_8;
CREATE DATABASE IF NOT EXISTS test_8;
USE test_8;

CREATE TABLE IF NOT EXISTS states ( 
    id INT NOT NULL AUTO_INCREMENT, 
    name VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);
